node {
    stage('Build') {
        sh 'mvn -B -DskipTests clean package'
    }

    stage('Test') {
        steps {
            sh 'mvn test'
        }
        post {
            always {
                junit 'target/surefire-reports/*.xml'
            }
        }
    }

    stage('display') {
        steps {
            sh 'echo we have completed the job'
        }
    }
}
